// React/app-users/src/Header.js
import React from "react";

import "./Header.css";

export default class Display extends React.Component {

  render() {
    return (
      <div className="display">
        <div>Mochan App<span><img src="https://media.licdn.com/dms/image/C560BAQH0jVKlRxGwyw/company-logo_200_200/0?e=2159024400&v=beta&t=1XL8mlQdD5PRXZPFk0PUFM1kCdznIQgGZ-SoBYzReIg" className="img"/></span></div>
      </div>

    );
  }

}

// Angular/app-angular/src/app/header/header.component.ts
import { Component, OnInit } from '@angular/core';


@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css']
})
export class HeaderComponent implements OnInit {
  title= 'Mochan App';

  constructor() {}

  ngOnInit() {
  }

}

<h1 class= "header">{{title}}<img src="https://media.licdn.com/dms/image/C560BAQH0jVKlRxGwyw/company-logo_200_200/0?e=2159024400&v=beta&t=1XL8mlQdD5PRXZPFk0PUFM1kCdznIQgGZ-SoBYzReIg" class="img"/></h1>
 <!-- <input type="text" name="" [value]="title">  -->
